// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('seleniumTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('seleniumTest', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1346, 740)
    await driver.findElement(By.id("emailInput")).click()
    await driver.findElement(By.id("emailInput")).sendKeys("yasser@gmail.com")
    await driver.findElement(By.id("passwordInput")).click()
    await driver.findElement(By.id("passwordInput")).sendKeys("yasser")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("noteCC")).click()
    await driver.findElement(By.id("noteCC")).sendKeys("15")
    await driver.findElement(By.id("noteCI")).click()
    await driver.findElement(By.id("noteCI")).sendKeys("10")
    await driver.findElement(By.id("noteCF")).click()
    await driver.findElement(By.id("noteCF")).sendKeys("20")
    await driver.findElement(By.css(".container-fluid:nth-child(2) #noteCC")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(2) #noteCC")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(2) #noteCC")).sendKeys("12")
    await driver.findElement(By.css(".container-fluid:nth-child(2) #noteCI")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(2) #noteCI")).sendKeys("16")
    await driver.findElement(By.css(".container-fluid:nth-child(2) #noteCF")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(2) #noteCF")).sendKeys("14")
    await driver.findElement(By.css(".container-fluid:nth-child(3) #noteCC")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(3) #noteCC")).sendKeys("19")
    await driver.findElement(By.css(".container-fluid:nth-child(3) #noteCI")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(3) #noteCI")).sendKeys("14")
    await driver.findElement(By.css(".container-fluid:nth-child(3) #noteCF")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(3) #noteCF")).sendKeys("16")
    await driver.findElement(By.css(".container-fluid:nth-child(4) #noteCC")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(4) #noteCC")).sendKeys("16")
    await driver.findElement(By.css(".container-fluid:nth-child(4) #noteCI")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(4) #noteCI")).sendKeys("11")
    await driver.findElement(By.css(".container-fluid:nth-child(4) #noteCF")).click()
    await driver.findElement(By.css(".container-fluid:nth-child(4) #noteCF")).sendKeys("17")
    await driver.findElement(By.id("myInput")).click()
    await driver.findElement(By.id("myInput")).sendKeys("Dba")
  })
})
